---
title: "Synthetic Bayes HMLR"
author: "Thomas Robacker"
date: "2024-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstan)
```

## Synthetic Bayesian HMLR Stan Fit

```{r}
setwd("~/Projects/rstanmodels/")
df <- suppressMessages(read_csv("./Data/syn_hmlr_dat.csv"))
head(df)
sum(is.na(df))
```

```{r}
df$clade <- as.numeric(as.factor(df$clade))
head(df)
```

```{r}
## Adapting to Copilot stan code!
# df is NxK indexed by date, will drop date for STAN input
df <- pivot_wider(df, names_from = clade, values_from = prop)
head(df) 

df_stan <- df[,-1]
head(df_stan)
```


```{r}
## Fit hmlr_stan

N <- dim(df_stan)[1]
K <- 3
#y <- df$prop
y <- as.matrix(df_stan*100) # converted to counts here 
colnames(y) <- NULL
storage.mode(y) <- "integer"

data_list <- list("N" = N, 
              "K" = K,
              "y" = y, 
              "time" = 1:10)

fit <- stan(
  file = "./Stan/hmlr_stan.stan",  # Stan program
  data = data_list, # named list of data
  chains = 1,             # number of Markov chains
  warmup = 1000,          # number of warmup iterations per chain
  iter = 4000,            # total number of iterations per chain
  refresh = 0             # no progress shown
)
```


```{r}
summary(fit)
```

```{r}
#launch_shinystan(fit)
```


```{r}
# Assuming 'fit' is the object containing the fitted STAN model
# Extract posterior samples
posterior_samples <- rstan::extract(fit)

# Extract the parameters
alpha_samples <- posterior_samples$alpha
gamma_samples <- posterior_samples$gamma
dim(alpha_samples)
```


```{r}
# Number of locations and categories
#L <- dim(alpha_samples)[2]
K <- dim(alpha_samples)[2] + 1

# Create a data frame for plotting
plot_data <- data.frame()


for (k in 1:(K-1)) {
  alpha_mean <- apply(alpha_samples, 2, mean)
  gamma_mean <- apply(gamma_samples, 2, mean)

  plot_data <- rbind(plot_data, data.frame(
    Category = k,
    Alpha = alpha_mean,
    Gamma = gamma_mean
  ))
}
head(plot_data)
```

```{r}
y1_pred <- c()
y2_pred <- c()
for(t in 1:10){
  y1_pred[t] <- alpha_mean[1] + t * gamma_mean[1]
  y2_pred[t] <- alpha_mean[2] + t * gamma_mean[2]
}
```



```{r}
# Plot the coefficients
ggplot(plot_data, aes(x = Category, y = Gamma, color = as.factor(Category))) +
  geom_point() +
  geom_line() +
  labs(title = "Time Coefficients by Location and Category",
       x = "Location",
       y = "Time Coefficient (Gamma)",
       color = "Category") +
  theme_minimal()
```



